set -ga terminal-overrides ",screen-256color*:Tc"

# Unbind CTRL + B
unbind C-b

# Set left alt as the new prefix
set-option -g prefix M

# Pane Motion
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Enable mouse scrolling
set -g mouse on

